version: '3'
services:
  service:
    build: .
    container_name: service
    depends_on:
      db:
        condition: service_healthy
    image: reshetnikovdimmi/website-tattoos:v1
    ports:
      - "8080:8080"
    volumes:
      - ~/data/images:/app/img/images
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/a0722849_maxsim
      - SPRING_DATASOURCE_USERNAME=a0722849_maxsim
      - SPRING_DATASOURCE_PASSWORD=R870nt55@
      - SPRING_MAIL_USERNAME=reshetnikov.dim.mi@yandex.ru
      - SPRING_MAIL_PASSWORD=kkrhwhlmoiawjgcm
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=a0722849_maxsim
      - MYSQL_USER=a0722849_maxsim
      - MYSQL_PASSWORD=R870nt55@
      - MYSQL_ROOT_PASSWORD=R870nt55@
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-uroot", "-pR870nt55@"]
      interval: 10s
      timeout: 5s
      retries: 5